# Generated by Django 3.0 on 2019-12-11 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(default=0, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
